# Generated by Django 5.2.1 on 2025-05-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0002_rename_member_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('pic', models.URLField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
    ]
