# Generated by Django 5.2.1 on 2025-05-17 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='person',
        ),
    ]
